n = int(input('Digite um número: '))

print('------- TABUADA DO {} -------'.format(n))
print(n, 'X 1 = {}'.format(n*1))
print(n, 'X 2 = {}'.format(n*2))
print(n, 'X 3 = {}'.format(n*3))
print(n, 'X 4 = {}'.format(n*4))
print(n, 'X 5 = {}'.format(n*5))
print(n, 'X 6 = {}'.format(n*6))
print(n, 'X 7 = {}'.format(n*7))
print(n, 'X 8 = {}'.format(n*8))
print(n, 'X 9 = {}'.format(n*9))
print(n, 'X 10 = {}'.format(n*10))
