0# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yirXpjm1yNLTkix5fNC8JmbNwrwNMT_3
"""



"""```
#Feedback PBL-2: em Grupo
# Algoritmo para testes se os valores A, B e C são lados de um triângulo
# Área de Variáveis
real LaodA, LadoB, LadoC
# Corpo do programa
imprimir("entre com o valor de A: ")
ler(LadoA)
imprimir("entre com o valor de B: ")
ler(LadoB)
imprimir("entre com o valor de C: ")
ler(LadoC)
Se (ABS(LadoB - LadoC) < LadoA) e ABS(LadoA - LadoC) < LadoB) e ABS(LadoA - LadoB) < LadoC) e ((LadoB + LadoC) > LadoA) e ((LadoA + LadoC) > LadoB) e ((LadoA + LadoB) > LadoC) então
      imprima("São lados de um triângulo!)
senão 
      imprima("Não são lados de um triângulo!")
fim se
imprima("Fim!")
```
"""

# Feedback PBL-2: em Grupo
# Algoritmo para testes se os valores A, B e C são lados de um triângulo
import math
# Corpo do programa
LadoA = float(input("Entre com o valor de A: "))
LadoB = float(input("Entre com o valor de B: "))
LadoC = float(input("Entre com o valor de C: "))
if (abs(LadoB - LadoC) < LadoA) and (abs(LadoA - LadoC) < LadoB) and (abs(LadoA - LadoB) < LadoC) and ((LadoB + LadoC) > LadoA) and ((LadoA + LadoC) > LadoB) and ((LadoA + LadoB) > LadoC):
      print("São lados de um triângulo!")
else: 
      print("Não são lados de um triângulo!")
print("Fim!")